#ifndef __VERSION_H__
#define __VERSION_H__
#define VERSION_DATE "Sat, 24 Aug 2013 18:20:33 +0200"
#define VERSION_HASH "UNKNOWN"
#define VERSION_BRANCH "UNKNOWN"
#define VERSION_REPO "UNKNOWN"
#endif
